### ISSUE TITLE
screwing with my recipes

### ISSUE THREAD

**Issue by beckyh2112** [SanAndreasP/VarietyChests#7]
Installed this and the API, logged into my world. For some reason, putting four planks in my crafting grid gives me two chests instead of a crafting table. Went out and re-tested in a world with just Variety Chests, SAPManPack, NEI, and WAILA. Same thing. Note that this only happens in your personal crafting grid - the recipe works just fine in a crafting table.

**Comment by SanAndreasP** [comment]
Will look into it.

**Comment by ZeroLevels** [comment]
Yeah, same for me.  It also heavily interferes with Minetweaker recipes and the like, pretty much rendering this mod unusable in modpacks, personal or otherwise.  Though, I have no idea if it would be this mod or the SanAndreasP Manager Pack, but removing them fixes the problem.  Hope this is looked into soon, as I've been looking for a mod that adds JUST these chests and looks good doing it.
